working_directory = "C:/Users/bobte"

[shell]
program = "C:/msys64/usr/bin/bash.exe"
args = ["--login","-i"]

[window]
dimensions = { columns = 115, lines = 30 }
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.7
dynamic_title = false

[font]
normal = { family = "Hack Nerd Font"}

[cursor]
style = { shape = "Block", blinking = "On"}